# watch_config_changes: Automatically reload borders whenever the config file is modified.
watch_config_changes: True

# rendering_backend: Type of renderer. Supported values:
#   - V2: A more complex, feature-rich renderer. Available in v1.2.0 and above.
#   - Legacy: A simpler, more limited renderer. Available in v0.1.0 and above.
#
# NOTE: Performance between the two may vary system-to-system. Choose whichever works best.
rendering_backend: V2

# Logging
enable_logging: True
# Global configuration options
global:
  # border_width: Width of the border (in pixels)
  border_width: 3

  # border_offset: Offset of the border from the window edges (in pixels)
  #   - Negative values shrink the border inwards
  #   - Positive values expand the border outwards
  border_offset: -1

  # border-radius: Radius of the border's corners. Supported values:
  #   - Auto: Automatically determine the radius
  #   - Square: Sharp corners (radius = 0)
  #   - Round: Fully rounded corners
  #   - RoundSmall: Slightly rounded corners
  #   - Or specify any numeric value for a custom radius
  border_radius: 0


  # border_z_order: Z-order of the border relative to its window. Supported values:
  #   - AboveWindow: Place the border above its window
  #   - BelowWindow: Place the border below its window
  #
  # NOTE: Using 'AboveWindow' may cause the border to flicker when used with some applications
  # that manipulate window layering, leading to z-order conflicts.
  border_z_order: BelowWindow

  # active_color: the color of the active window's border
  # inactive_color: the color of the inactive window's border
  #
  # Supported color types:
  #   - Solid: Use a hex code or "accent"
  #       Example:
  #         active_color: "#ffffff"
  #         OR2
  #         active_color: "accent"
  #   - Gradient: Define colors and direction
  #       Example:
  #         active_color:
  #           colors: ["#000000", "#ffffff"]
  #           direction: 45deg
  #         OR
  #         active_color:
  #           colors: ["#000000", "#ffffff"]
  #           direction:
  #             start: [0.0, 1.0]
  #             end: [1.0, 0.0]
  #       NOTE: [0.0, 0.0] = top-left, [1.0, 1.0] = bottom-right
  active_color: "#FFFFFF"
  inactive_color: "#A0A0A0"

  # initialize_delay: Time (in ms) before the border appears after opening a new window
  # unminimize_delay: Time (in ms) before the border appears after unminimizing a window
  #
  # These settings help accommodate window animations (e.g., open or unminimize animations).
  # If window animations are disabled, set these to 0.
  #
  # These can also be used to accomodate border animations (e.g., fade animations).
  initialize_delay: 0
  unminimize_delay: 0

    # follow_native_border: Follow Windows' behavior for border visibility.
  #
  # Windows already shows or hides native borders depending on a window's type or state
  # (e.g., they're hidden for borderless fullscreen windows). When enabled, this option makes
  # tacky-borders follow that visibility behavior.
  #
  # NOTE: This setting only affects visibility for borders that have been initialized.
  # To make sure a border is initialized in the first place, use window_rules.
  follow_native_border: True

  # Effects
  effects:
    active:
      - type: Shadow
        blur: 2
        spread: 4
        opacity: 1.0
    
    inactive:
      - type: Shadow
        blur: 2
        spread: 4
        opacity: 1.0
    enabled: True

# Per-application configuration overrides
window_rules:
  - match: Class
    name: "Windows.UI.Core.CoreWindow"
    enabled: False

  - match: Class
    name: "XamlExplorerHostIslandWindow"
    enabled: False

  - match: Process
    name: "zebar"
    enabled: False

  - match: Title
    name: "komorebi-bar"
    enabled: False

  - match: Title
    name: "keyviz"
    enabled: False

  - match: Title
    name: "Picture-in-Picture"
    enabled: False
  
  - match: Process
    name: "tacky-borders"
    enabled: False
  
  - match: Process
    name: "seelen-ui"
    enabled: False

  # Example rule:
  # - match: Class                   # Match based on Class or Title
  #   name: "MozillaWindowClass"     # Class or title name to match
  #   strategy: Equals               # Matching strategy: Equals, Contains, or Regex (default: Equals)
  #   enabled: True                  # Border enabled: True, False, or Auto (default: Auto)
  #
  # Notes:
  #   - Any option in the global config can also be defined in window_rules.
  #   - If not defined in a rule, settings will fall back to global config values.
